### ISSUE TITLE
 no element "Item Type Metadata", "Content

### ISSUE THREAD

**Issue by allamiro** [BGSU-LITS/Digital-Gallery-Theme#1]
exception 'Omeka_Record_Exception' with message 'There is no element "Item Type Metadata", "Content"!' in /home1/application/models/Mixin/ElementText.php:293

**Comment by kloor** [comment]
This is an older project that likely will not work with newer versions of Omeka, and will probably not be of much interest to users outside of Bowling Green State University. We will not be providing any support for the project.
